kneaddata_db: /crex/proj/uppstore2017185/b2014034_nobackup/Dasha/AIT_meta/hg_39
kraken2_db: /sw/data/Kraken2_data/prebuilt/k2_standard_08gb_20240112
bracken_db: /sw/data/Kraken2_data/prebuilt/k2_standard_08gb_20240112
